[[what-is-promise]]
== What Is Promise

首先让我们来了解一下到底什么是Promise呢？

Promise是抽象非同期处理的对象以及对其进行各种操作的组件。
其详细内容在接下来我们还会学到，Promise并不是从JavaScript中发现的概念。

最初被发现是在 http://erights.org/elib/distrib/pipeline.html[E言語]中，
它是基于并列/并行处理设计的一种编程语言。

JavaScript也拥有了这种特性，这就是本书所介绍的JavaScript Promise。

另外，如果说到基于JavaScript的非同期处理，我想大多数都会利用回调函数。

[source,javascript]
.使用了回调函数的非同期处理
----
getAsync("fileA.txt", function(error, result){// <1>
    if(error){// 取得失败时的处理
        throw error;
    }
    // 取得成功时的处理
});
----
<1> 回调函数的参数中加入(error对象， 结果)

像Node.js等在JavaScript的回调函数的第一个参数里传入 `Error` 对象成为规则的例子也有。

像回调函数的非同期处理一样规则统一的话，写法就会很明确。
但是，这也仅是编码规约，即使用不同的写法也不会出错。

Promise，把非同期对象和规则确定式样，
并用统一的接口来写，不可以用除此以外的写法。

[source,javascript]
用了.Promise的非同期例子
----
var promise = getAsyncPromise("fileA.txt"); // <1>
promise.then(function(result){
    // 取得成功时的处理
}).catch(function(error){
    // 取得失败时的处理
});
----
<1> 返回promise对象

非同期処理を抽象化したpromiseオブジェクトというものを用意し、
そのpromiseオブジェクトに対して成功時の処理と失敗時の処理の関数を登録するようにして使います。

コールバック関数と比べると何が違うのかを簡単に見ると、
非同期処理の書き方がpromiseオブジェクトのインターフェースに沿った書き方に限定されます。

つまり、promiseオブジェクトに用意されてるメソッド(ここでは `then` や `catch`)以外は使えないため、
コールバックのように引数に何を入れるかが自由に決められるわけではなく、一定のやり方に統一されます。

この、Promiseという統一されたインターフェースがあることで、
そのインターフェースにおける様々な非同期処理のパターンを形成することが出来ます。

つまり、複雑な非同期処理等を上手くパターン化できるというのがPromiseの役割であり、
Promiseを使う理由の一つであるといえるでしょう。

それでは、実際にJavaScriptでのPromiseについて学んでいきましょう。
