[[what-is-promise]]
== What Is Promise

首先让我们来了解一下到底什么是Promise呢？

Promise是抽象非同期处理的对象以及对其进行各种操作的组件。
其详细内容在接下来我们还会学到，Promise并不是从JavaScript中发现的概念。

最初被发现是在 http://erights.org/elib/distrib/pipeline.html[E言語]中，
它是基于并列/并行处理设计的一种编程语言。

JavaScript也拥有了这种特性，这就是本书所介绍的JavaScript Promise。

另外，如果说到基于JavaScript的非同期处理，我想大多数都会利用回调函数。

[source,javascript]
.使用了回调函数的非同期处理
----
getAsync("fileA.txt", function(error, result){// <1>
    if(error){// 取得失敗時の処理
        throw error;
    }
    // 取得成功の処理
});
----
<1> コールバック関数の引数には(エラーオブジェクト, 結果)が入る

Node.js等JavaScriptでのコールバック関数の第一引数には `Error` オブジェクトを渡すというルールを用いるケースがあります。

このようにコールバックでの非同期処理もルールが統一されていた場合、コールバック関数の書き方が明確になります。
しかし、これはあくまでコーディングルールであるため、異なる書き方をしても決して間違いではありません。

Promiseでは、このような非同期に対するオブジェクトとルールを仕様化して、
統一的なインターフェースで書くようになっており、それ以外の書き方は出来ないようになっています。

[source,javascript]
.Promiseを使った非同期処理の一例
----
var promise = getAsyncPromise("fileA.txt"); // <1>
promise.then(function(result){
    // 取得成功の処理
}).catch(function(error){
    // 取得失敗時の処理
});
----
<1> promiseオブジェクトを返す

非同期処理を抽象化したpromiseオブジェクトというものを用意し、
そのpromiseオブジェクトに対して成功時の処理と失敗時の処理の関数を登録するようにして使います。

コールバック関数と比べると何が違うのかを簡単に見ると、
非同期処理の書き方がpromiseオブジェクトのインターフェースに沿った書き方に限定されます。

つまり、promiseオブジェクトに用意されてるメソッド(ここでは `then` や `catch`)以外は使えないため、
コールバックのように引数に何を入れるかが自由に決められるわけではなく、一定のやり方に統一されます。

この、Promiseという統一されたインターフェースがあることで、
そのインターフェースにおける様々な非同期処理のパターンを形成することが出来ます。

つまり、複雑な非同期処理等を上手くパターン化できるというのがPromiseの役割であり、
Promiseを使う理由の一つであるといえるでしょう。

それでは、実際にJavaScriptでのPromiseについて学んでいきましょう。
